### ISSUE TITLE
Errores en validación w3c del fichero profile.html

### ISSUE THREAD

**Issue by raquelrh** [osperi/Avengers#24]
Cuando se ha validado el fichero profile.html se ha visto que la etiqueta  `</br>` es incorrecta debería ser  `<br/>`.
También el tag del title "Mi Perfil" el `<h5>`, la tag de cerrado es incorrecta, ya que pone `</h3>`

**Comment by hectorri** [comment]
Incidencia resuelta en el pull https://github.com/osperi/Avengers/pull/26 a la espera de aprobación.

**Comment by raquelrh** [comment]
Se ha comprobado que el error se ha sido corregido. Se cierra la incidencia
